CREATE OR REPLACE FUNCTION ENTRATE(DATA_INIZIALE DATE,DATA_FINE DATE)
RETURN NUMBER IS ENTRATE NUMBER;
BEGIN
ENTRATE:=0; /* IL PREZZO VENDITA DI UN ARTICOLO VIENE CALCOLATO IN QUESTO MODO: SI MOLTIPLICA PREZZO ACQUISTO CON IVA * ( PREZZO ACQUISTO CON IVA * IVA) SICCOME SI VUOLE CONOSCERE IL GUADAGNO SU UNA CERTA QUANTITA' DI PRODOTTI VENDUTI SI MOLTIPLICA LA QUANTITA VENDUTA PER PREZZO VENDITA. L'ENTRATE PERIODICA E' DATA DALLA SOMMA DELLE QTVENDUTA*PREZZOVENDITA PER CIASCUN ARTICOLO*/ 
SELECT ROUND(SUM(R.QTVENDUTA*((C.PREZZOCU+(C.PREZZOCU*F.IVA/100))+((C.PREZZOCU+(C.PREZZOCU*F.IVA/100))*F.IVA/100))),2) 
INTO ENTRATE 
FROM ARTICOLO A JOIN FAMIGLIA_ASSORTIMENTO F ON F.IDFAMASS=A.IDFAMASS 
				JOIN RIGUARDA R ON R.CODART=A.CODART 
				JOIN MOVIMENTO M ON M.COD_MOVIMENTO=R.COD_MOVIMENTO 
				JOIN CONTIENE C ON C.CODART=A.CODART 
WHERE M.DATA_STAMPA BETWEEN DATA_INIZIALE AND DATA_FINE AND 
	C.DATA_EMISSIONE=
	(SELECT MAX(DATA_EMISSIONE) 
	  FROM CONTIENE 
	  WHERE CODART=A.CODART AND DATA_EMISSIONE<DATA_FINE);
 -- SI PRELEVA IL PREZZOCU RELATIVO ALL'ULTIMO RIFORNIMENTO
 -- PER QUELL'ARTICOLO EFFETTUATO IN UNA DATA PRECEDENTE 
 -- DATA FINE. 
 RETURN ENTRATE;
 END;
 /