CREATE OR REPLACE FUNCTION ENTRATE_PEGNI(DATA_INIZIALE DATE, DATA_FINE DATE) 
RETURN NUMBER IS ENT_PEGNI NUMBER; 
BEGIN 
ENT_PEGNI:=0; 
FOR P IN (SELECT P.DATA_PEGNO,P.IMPORTO FROM PEGNO P WHERE P.DATA_PEGNO BETWEEN DATA_INIZIALE AND DATA_FINE)
 LOOP ENT_PEGNI:=ENT_PEGNI+MATURATOPEGNI(P.DATA_PEGNO,P.IMPORTO);
 END LOOP;
 RETURN ENT_PEGNI;
 END;
 /