CREATE OR REPLACE PROCEDURE SCRIVIRISCATTO(CODP PEGNO.COD_PEGNO%TYPE) 
IS DIP DIPENDENTE.CF%TYPE;
 MATURATO NUMBER; 
 DATAP PEGNO.DATA_PEGNO%TYPE; 
 IMP PEGNO.IMPORTO%TYPE; 
 PGNEXPT EXCEPTION;
 DIPEXPT EXCEPTION; 
 PRAGMA EXCEPTION_INIT(DIPEXPT, -2291); 
 COD_RIS RISCATTO.COD_RISCATTO%TYPE; 
 BEGIN 
 MATURATO:=0;
 DIP:=USER; 
 SELECT COD_RISCATTO INTO COD_RIS 
 FROM RISCATTO
WHERE COD_PEGNO=CODP; 
IF COD_RIS>0 THEN RAISE PGNEXPT; 
END IF;
 EXCEPTION 
 WHEN PGNEXPT THEN RAISE_APPLICATION_ERROR(-20102,'ATTENZIONE: OGGETTO GIA RISCATTATO'); 
 -- GESTIONE DELL'ECCEZIONE NO ROWS SELECTED 
 -- CHE POTREBBE ESSERE LANCIATA QUANDO UN OGGETTO NON E' STATO MAI RISCATTATO 
 -- INIZIO UN BLOCCO ANONIMO PER GESTIRE LE ECCEZIONI CHE POTREBBERO ESSERE 
 -- LANCIATE IN QUESTA FASE DI INSERIMENTO 
 WHEN NO_DATA_FOUND THEN BEGIN SAVEPOINT A; 
 SELECT DATA_PEGNO,IMPORTO INTO DATAP,IMP 
 FROM PEGNO 
 WHERE COD_PEGNO=CODP;
 MATURATO:=MATURATOPEGNI(DATAP,IMP);
 INSERT INTO RISCATTO(COD_RISCATTO,COD_PEGNO,DATA_RISCATTO,MATURATO,CF_DIP)
 VALUES(SEQ_CODRISCATTO.NEXTVAL,CODP,SYSDATE,MATURATO,DIP);
 COMMIT; 
 EXCEPTION 
 WHEN DIPEXPT THEN DBMS_OUTPUT.PUT_LINE('ATTENZIONE: DIPENDENTE NON AUTORIZZATO');
 ROLLBACK TO A; 
 END;
 END;
 /
 