CREATE OR REPLACE PROCEDURE NUOVO_CLIENTE_PEGNO(
CODF PERSONA.CODICE_FISCALE%TYPE,
N PERSONA.NOME%TYPE,
C PERSONA.COGNOME%TYPE,
V PERSONA.VIA%TYPE,
CI PERSONA.CITTA%TYPE,
CA PERSONA.CAP%TYPE,
CIV PERSONA.CIVICO%TYPE,
DN PERSONA.DATA_NASCITA%TYPE,
SEX PERSONA.SESSO%TYPE,
IMP PEGNO.IMPORTO%TYPE,
TI OGGETTO.TIPO%TYPE,
COD_OGG OGGETTO.COD_OGGETTO%TYPE,
M OGGETTO.MARCA%TYPE,
MO OGGETTO.MODELLO%TYPE,
MAT OGGETTO.MATERIALE%TYPE,
CC CONSULENZA.COD_CONSULENZA%TYPE) IS
DIP VARCHAR2(40);
CODPGN NUMBER;
BEGIN
DIP:=USER; SAVEPOINT A;
INSERT INTO PERSONA(CODICE_FISCALE,NOME,COGNOME,VIA,CITTA, CAP,CIVICO,DATA_NASCITA,SESSO)VALUES(CODF,N,C,V,CI,CA,CIV,DN,SEX);
INSERT INTO CLIENTE(CF,DATA_REGISTRAZIONE)VALUES(CODF,SYSDATE); CODPGN:=SEQ_CODPEGNO.NEXTVAL;
INSERT INTO PEGNO(COD_PEGNO,CF_DIP,CF_CLI,DATA_PEGNO,IMPORTO)VALUES(CODPGN,DIP,CODF,SYSDATE,IMP);
INSERT INTO OGGETTO(COD_PEGNO,COD_OGGETTO,TIPO,MARCA,MODELLO,MATERIALE,COD_CONSULENZA)VALUES(CODPGN,COD_OGG,TI,M,MO,MAT,CC);
COMMIT;
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN DBMS_OUTPUT.PUT_LINE('ATTENZIONE: CLIENTE GIA REGISTRATO');
ROLLBACK TO A;
END;
/
