CREATE OR REPLACE PROCEDURE CREA_MOVIMENTO
IS
DIP DIPENDENTE.CF%TYPE;
COD MOVIMENTO.COD_MOVIMENTO%TYPE;
EX1 EXCEPTION;
BEGIN
DIP:=USER;
SELECT COD_MOVIMENTO INTO COD FROM MOVIMENTO WHERE TO_CHAR(DATA_STAMPA,'DD- MM-YYYY')=TO_CHAR(SYSDATE,'DD-MM-YYYY');
IF COD !=0 THEN RAISE EX1;
END IF;
EXCEPTION WHEN NO_DATA_FOUND THEN
INSERT INTO MOVIMENTO(COD_MOVIMENTO,DATA_STAMPA,CF_DIP)VALUES(SEQ_CODMOVIMENTO.NEXTVAL,SYSDATE,DIP);
COMMIT;
WHEN EX1 THEN
RAISE_APPLICATION_ERROR(-20200,'ATTENZIONE: MOVIMENTO PER LA DATA '||SYSDATE||' GIA REGISTRATO');
END;
/