CREATE OR REPLACE PROCEDURE INSERISCI_FATTURA(DATAE FATTURA.DATA_EMISSIONE%TYPE,DATAS FATTURA.DATA_SCADENZA%TYPE,PIVA FATTURA.PIVA%TYPE)
IS
DIP DIPENDENTE.CF%TYPE;
EX1 EXCEPTION;
PRAGMA EXCEPTION_INIT(EX1,-2291);
 BEGIN
DIP:=USER; 
INSERT INTO FATTURA(DATA_EMISSIONE,DATA_SCADENZA,PIVA,CF_DIP)VALUES(DATAE,DATAS,PIVA,DIP);
EXCEPTION
WHEN DUP_VAL_ON_INDEX THEN
RAISE_APPLICATION_ERROR(-20003,'ATTENZIONE: FATTURA GIA REGISTRATA');
WHEN EX1 THEN
RAISE_APPLICATION_ERROR(-20019,'ATTENZIONE: FORNITORE [PIVA] NON REGISTRATO');
END;

/