CREATE OR REPLACE PROCEDURE ECONOMIA_PERIODICA(DATA_INIZIALE DATE,DATA_FINE DATE)
IS
E NUMBER;
U NUMBER;
EX1 EXCEPTION; 
TMP NUMBER; 
EX2 EXCEPTION; 
EX3 EXCEPTION; 
BEGIN
E:=ENTRATE(DATA_INIZIALE,DATA_FINE); 
IF E IS NULL THEN
RAISE EX1; 
END IF; 
TMP:=E;
E:=E+ENTRATE_PEGNI(DATA_INIZIALE,DATA_FINE); 
IF E=TMP THEN
RAISE EX2; 
END IF;
U:=USCITE(DATA_INIZIALE,DATA_FINE); 
IF U IS NULL THEN
RAISE EX3; 
END IF;
DBMS_OUTPUT.PUT_LINE('SITUAZIONE ECONOMICA PERIODO '||DATA_INIZIALE ||' - '||DATA_FINE);
DBMS_OUTPUT.PUT_LINE('ENTRATE: '||ROUND(E,2)); DBMS_OUTPUT.PUT_LINE('USCITE: '||ROUND(U,2));
EXCEPTION
WHEN EX1 THEN
DBMS_OUTPUT.PUT_LINE(' NON SONO STATI VENDUTI ARTICOLI'); 
WHEN EX2 THEN
DBMS_OUTPUT.PUT_LINE(' NON CI SONO STATI RISCATTI'); 
WHEN EX3 THEN
DBMS_OUTPUT.PUT_LINE(' NON CI SONO STATI RIFORNIMENTI'); 
END;
/
