CREATE OR REPLACE PROCEDURE SCRIVI_PEGNO(CF CLIENTE.CF%TYPE,CO OGGETTO.COD_OGGETTO%TYPE,TI OGGETTO.TIPO%TYPE,M OGGETTO.MARCA%TYPE,
MO OGGETTO.MODELLO%TYPE,MA OGGETTO.MATERIALE%TYPE,CC OGGETTO.COD_CONSULENZA%TYPE,IMP PEGNO.IMPORTO%TYPE)
IS
CODPGN NUMBER;
DIP DIPENDENTE.CF%TYPE; 
BEGIN
DIP:=USER; 
CODPGN:=SEQ_CODPEGNO.NEXTVAL; 
SAVEPOINT A;
INSERT INTO PEGNO(COD_PEGNO,CF_DIP,CF_CLI,DATA_PEGNO,IMPORTO)VALUES(CODPGN,DIP,CF,SYSDATE,IMP);
INSERT INTO OGGETTO(COD_PEGNO,COD_OGGETTO,TIPO,MARCA,MODELLO,MATERIALE,COD_CONSULENZA)VALUES(CODPGN,CO,TI,M,MO,MA,CC); 
COMMIT;
END;
/
