CREATE OR REPLACE PROCEDURE ELIMINA_DIPENDENTE(C DIPENDENTE.CF%TYPE) IS
CODF DIPENDENTE.CF%TYPE;
BEGIN
SELECT CF INTO CODF FROM DIPENDENTE WHERE CF=C;
IF CODF IS NOT NULL THEN
DELETE FROM DIPENDENTE
WHERE CF=C;
END IF;
COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-20468,'ATTENZIONE: DIPENDENTE NON REGISTRATO');
END;
/