--1.	Aggiornamento report vendite annuali 
BEGIN 
DBMS_SCHEDULER.CREATE_JOB(
JOB_NAME	=> 'REFRESH_VENDITE_ANNUALI',
JOB_TYPE	=> 'STORED_PROCEDURE',
JOB_ACTION	=> 'REFRESH_MV_RVA', 
NUMBER_OF_ARGUMENTS => 0,
START_DATE	=> TO_DATE('31-12-2018 21:00:00','DD-MM-YYYY hh24:mi:ss'),
REPEAT_INTERVAL	=> 'FREQ=YEARLY;', 
END_DATE	=> NULL,
ENABLED	=> TRUE,
AUTO_DROP	=> FALSE,
COMMENTS	=> 'QUESTO JOB AGGIORNA LE VENDITA DEI PRODOTTI ANNUALI'
); 
END;
/

--2.	Aggiornamento report pegni riscattati 
BEGIN 
DBMS_SCHEDULER.CREATE_JOB(
JOB_NAME	=> 'REFRESH_PEGNI_RISCATTI_ANNUALI',
JOB_TYPE	=> 'STORED_PROCEDURE', 
JOB_ACTION	=> 'REFRESH_MV_PEGNI_RISCATTI', 
NUMBER_OF_ARGUMENTS => 0,
START_DATE	=> TO_DATE('31-12-2018 21:00:00','DD-MM-YYYY hh24:mi:ss'),
REPEAT_INTERVAL	=> 'FREQ=YEARLY;', 
END_DATE	=> NULL,
ENABLED	=> TRUE,
AUTO_DROP	=> FALSE,
COMMENTS	=> 'QUESTO JOB AGGIORNA IL REPORT RELATIVO AI PEGNI RISCATTATI ANNUALI'
); 
END;
/

--3.	Aggiornamento report oggetti non riscattati di pegni scaduti
BEGIN
DBMS_SCHEDULER.CREATE_JOB(
JOB_NAME	=> 'REFRESH_OGGETTI_NON_RISCATTATI',
JOB_TYPE	=> 'STORED_PROCEDURE',
JOB_ACTION	=> 'REFRESH_MV_ONR', 
NUMBER_OF_ARGUMENTS => 0,
START_DATE	=> TO_DATE('31-12-2018 21:40:00','DD-MM-YYYY hh24:mi:ss'),
REPEAT_INTERVAL	=> 'FREQ=YEARLY;', 
END_DATE	=> NULL,
ENABLED	=> TRUE,
AUTO_DROP	=> FALSE,
COMMENTS	=> 'QUESTO JOB AGGIORNA GLI OGGETTI NON RISCATTATI'
);
END;
 /
--4.	Roll out Pegni Riscattati
BEGIN
DBMS_SCHEDULER.CREATE_JOB(
JOB_NAME	=> 'ROLLOUT_PEGNI',
JOB_TYPE	=> 'PLSQL_BLOCK',
JOB_ACTION	=> 'BEGIN DELETE FROM PEGNO
					WHERE COD_PEGNO IN ( SELECT
					COD_PEGNO FROM RISCATTO)', 
NUMBER_OF_ARGUMENTS => 0,
START_DATE	=> TO_DATE('31-12-2018 21:30:00','DD-MM-YYYY hh24:mi:ss'),
REPEAT_INTERVAL	=> 'FREQ=YEARLY;', 
END_DATE	=> NULL,
ENABLED	=> TRUE,
AUTO_DROP	=> FALSE,
COMMENTS	=> 'QUESTO JOB ELIMINA DALLA TABELLA PEGNI TUTTI QUELLI CHE SONO STATI RISCATTATI'
); 
END;
/
--5.	Roll out Pegni Scaduti
BEGIN
DBMS_SCHEDULER.CREATE_JOB(
JOB_NAME	=> 'ROLLOUT_PEGNI_NNRISCATTATI',
JOB_TYPE	=> 'PLSQL_BLOCK',
JOB_ACTION	=> 'BEGIN
 DELETE FROM PEGNO
WHERE COD_PEGNO IN ( SELECT
COD_PEGNO FROM OGGETTI_NON_RISCATTATI)', 
NUMBER_OF_ARGUMENTS => 0,
START_DATE	=> TO_DATE('31-12-2018 21:42:00','DD-MM-YYYY hh24:mi:ss'),
REPEAT_INTERVAL	=> 'FREQ=YEARLY;', 
END_DATE	=> NULL,
ENABLED	=> TRUE,
AUTO_DROP	=> FALSE,
COMMENTS	=> 'QUESTO JOB ELIMINA DALLA TABELLA PEGNI TUTTI QUELLI CHE NON SONO STATI RISCATTATI'
);
END;
/
--6.	Roll out Riscatti
BEGIN
DBMS_SCHEDULER.CREATE_JOB(
JOB_NAME	=> 'ROLLOUT_RISCATTI',
JOB_TYPE	=> 'PLSQL_BLOCK',
JOB_ACTION	=> 'BEGIN
				DELETE FROM RISCATTO 
				WHERE COD_PEGNO IS NULL',
NUMBER_OF_ARGUMENTS => 0,
START_DATE	=> TO_DATE('31-12-2018 21:33:00','DD-MM-YYYY hh24:mi:ss'),
REPEAT_INTERVAL	=> 'FREQ=YEARLY;', 
END_DATE	=> NULL,
ENABLED	=> TRUE,
AUTO_DROP	=> FALSE,
COMMENTS	=> 'QUESTO JOB ELIMINA DALLA TABELLA RISCATTO TUTTI LE RIGHE CON COD_PEGNO NULL'
);
END;
/