DROP TABLE TELEFONOFORNITORI;
DROP TABLE TELEFONOPERSONA;
DROP TABLE TELEFONOESPERTO;
DROP TABLE OGGETTO;
DROP TABLE RISCATTO;
DROP TABLE PEGNO;
DROP TABLE RIGUARDA;
DROP TABLE CONTIENE;
DROP TABLE ARTICOLO;
DROP TABLE FAMIGLIA_ASSORTIMENTO;
DROP TABLE FATTURA;
DROP TABLE MOVIMENTO;
DROP TABLE FORNITORE;
DROP TABLE PRESENZA;
DROP TABLE CLIENTE;
DROP TABLE VALUTA;
DROP TABLE CONSULENZA;
DROP TABLE CATEGORIA;
DROP TABLE ESPERTO;
DROP TABLE DIPENDENTE;
DROP TABLE PERSONA;



CREATE TABLE FAMIGLIA_ASSORTIMENTO( 
IDFAMASS NUMBER,
IVA NUMBER NOT NULL,
NOME VARCHAR2(100) NOT NULL,
CONSTRAINT PK_FAMASS PRIMARY KEY (IDFAMASS));

CREATE TABLE ARTICOLO(
NOME VARCHAR2(30) NOT NULL,
MARCA VARCHAR2(30),
CODART NUMBER,
IDFAMASS NUMBER,
CONSTRAINT PK_ARTICOLO PRIMARY KEY (CODART),
CONSTRAINT FK_FAMASS FOREIGN KEY(IDFAMASS) REFERENCES FAMIGLIA_ASSORTIMENTO(IDFAMASS) ON DELETE SET NULL);

CREATE TABLE PERSONA(
NOME VARCHAR2(30) NOT NULL,
COGNOME VARCHAR2(30) NOT NULL,
CODICE_FISCALE CHAR(16),
VIA VARCHAR2(30),
CITTA VARCHAR2(30),
CAP CHAR(8),
CIVICO NUMBER,
DATA_NASCITA DATE NOT NULL,
SESSO CHAR(1) NOT NULL,
CONSTRAINT CHK_SESSO CHECK(SESSO in ('M','F')),
CONSTRAINT PK_PERSONA PRIMARY KEY(CODICE_FISCALE));

CREATE TABLE DIPENDENTE(
CF CHAR(16),
DATA_ASSUNZIONE DATE NOT NULL,
STIPENDIO NUMBER NOT NULL,
CONSTRAINT PK_DIPENDENTE PRIMARY KEY(CF),
CONSTRAINT FK_CF FOREIGN KEY (CF) REFERENCES PERSONA(CODICE_FISCALE) ON DELETE CASCADE);

CREATE TABLE CLIENTE(
CF CHAR(16),
DATA_REGISTRAZIONE DATE NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY(CF),
CONSTRAINT FK_CF2 FOREIGN KEY(CF) REFERENCES PERSONA(CODICE_FISCALE) ON DELETE CASCADE);

CREATE TABLE FORNITORE(
PIVA CHAR(11),
NOME VARCHAR2(30) NOT NULL,
VIA VARCHAR2(30),
CIVICO NUMBER,
CAP CHAR(6),
CITTA VARCHAR2(30),
IBAN CHAR(27) NOT NULL,
CONSTRAINT PK_FORNITORE PRIMARY KEY(PIVA));

CREATE TABLE FATTURA(
DATA_EMISSIONE DATE,
DATA_SCADENZA DATE,
PIVA CHAR(11),
CF_DIP CHAR(16),
CONSTRAINT FK_CFDIP1 FOREIGN KEY(CF_DIP) REFERENCES DIPENDENTE(CF) ON DELETE SET NULL,
CONSTRAINT PK_FATTURA PRIMARY KEY(DATA_EMISSIONE,PIVA),
CONSTRAINT FK_FORNITORE FOREIGN KEY(PIVA) REFERENCES FORNITORE(PIVA) ON DELETE SET NULL);

CREATE TABLE MOVIMENTO(
COD_MOVIMENTO NUMBER,
DATA_STAMPA DATE NOT NULL,
CF_DIP CHAR(16),
CONSTRAINT PK_MOVIMENTO PRIMARY KEY(COD_MOVIMENTO),
CONSTRAINT FK_CFDIP2 FOREIGN KEY(CF_DIP) REFERENCES DIPENDENTE(CF) ON DELETE SET NULL);

CREATE TABLE RIGUARDA(
COD_MOVIMENTO NUMBER,
CODART NUMBER,
QTVENDUTA NUMBER NOT NULL,
CONSTRAINT PK_RIGUARDA PRIMARY KEY (COD_MOVIMENTO,CODART),
CONSTRAINT FK_CODMOV FOREIGN KEY(COD_MOVIMENTO) REFERENCES MOVIMENTO(COD_MOVIMENTO) ON DELETE SET NULL,
CONSTRAINT FK_CODART FOREIGN KEY(CODART) REFERENCES ARTICOLO(CODART) ON DELETE SET NULL);

CREATE TABLE CONTIENE(
PIVA CHAR(11),
DATA_EMISSIONE DATE,
CODART NUMBER,
QTACQUISTATA NUMBER NOT NULL,
PREZZOCU NUMBER NOT NULL,
CONSTRAINT PK_CONTIENE PRIMARY KEY(PIVA,DATA_EMISSIONE,CODART),
CONSTRAINT FK_PIVAFATTURA FOREIGN KEY (DATA_EMISSIONE,PIVA) REFERENCES FATTURA(DATA_EMISSIONE,PIVA) ON DELETE SET NULL);

CREATE TABLE PRESENZA(
DATA_E_ORA_INIZIO DATE,
DATA_E_ORA_FINE DATE,
CF_DIP CHAR(16) NOT NULL,
CONSTRAINT PK_PRESENZA PRIMARY KEY(DATA_E_ORA_INIZIO,CF_DIP),
CONSTRAINT FK_CFDIP3 FOREIGN KEY(CF_DIP) REFERENCES DIPENDENTE(CF) ON DELETE CASCADE);

CREATE TABLE PEGNO(
COD_PEGNO NUMBER,
CF_DIP CHAR(16),
CF_CLI CHAR(16),
DATA_PEGNO DATE NOT NULL,
IMPORTO NUMBER NOT NULL,
PROROGA CHAR(1),
CONSTRAINT PK_PEGNO PRIMARY KEY (COD_PEGNO),
CONSTRAINT FK_CFDIP4 FOREIGN KEY(CF_DIP) REFERENCES DIPENDENTE(CF) ON DELETE SET NULL,
CONSTRAINT FK_CFCLI1 FOREIGN KEY(CF_CLI) REFERENCES CLIENTE(CF) ON DELETE SET NULL);

CREATE TABLE RISCATTO(
COD_RISCATTO NUMBER,
COD_PEGNO NUMBER,
DATA_RISCATTO DATE,
MATURATO NUMBER NOT NULL,
CF_DIP CHAR(16),
CONSTRAINT PK_RISCATTO PRIMARY KEY(COD_RISCATTO),
CONSTRAINT FK_PEGNO1 FOREIGN KEY(COD_PEGNO) REFERENCES PEGNO(COD_PEGNO) ON DELETE SET NULL,
CONSTRAINT FK_CFDIP5 FOREIGN KEY(CF_DIP) REFERENCES DIPENDENTE(CF) ON DELETE SET NULL);
-------------------------------------------------------------------------------------------

CREATE TABLE ESPERTO (
NOME VARCHAR2(30) NOT NULL,
COGNOME VARCHAR2(30)NOT NULL,
CF CHAR(16),
CF_DIP CHAR(16) NOT NULL,
CONSTRAINT PK_ESPERTO PRIMARY KEY(CF),
CONSTRAINT FK_CFDIP6 FOREIGN KEY(CF_DIP) REFERENCES DIPENDENTE(CF) ON DELETE CASCADE);

CREATE TABLE CONSULENZA(
COD_CONSULENZA CHAR(10),
CF_ESPERTO CHAR(16),
DATAPAGAMENTO DATE NOT NULL,
DATACONSULENZA DATE NOT NULL,
LIVUSURASTIMATO CHAR(1) NOT NULL,
STIMAIMPORTO NUMBER,
CONSTRAINT CHK_OGGETTO1 CHECK( LIVUSURASTIMATO IN('A','B','C')),
CONSTRAINT PK_CONSULENZA PRIMARY KEY(COD_CONSULENZA),
CONSTRAINT FK_CFESP1 FOREIGN KEY(CF_ESPERTO) REFERENCES ESPERTO(CF) ON DELETE CASCADE);

CREATE TABLE OGGETTO(
COD_PEGNO NUMBER NOT NULL,
COD_OGGETTO CHAR (10),
TIPO CHAR(1) NOT NULL,
MARCA VARCHAR2 (20),
MODELLO VARCHAR2 (20),
MATERIALE VARCHAR (20),
COD_CONSULENZA CHAR(10) NOT NULL,
CONSTRAINT PK_OGGETTO PRIMARY KEY(COD_OGGETTO),
CONSTRAINT CHK_OGGETTO2 CHECK( TIPO IN('1','0')), -- 0 PREZIOSO 1 ELETTRONICA
CONSTRAINT FK_PEGNO2 FOREIGN KEY(COD_PEGNO) REFERENCES PEGNO(COD_PEGNO) ON DELETE CASCADE,
CONSTRAINT FK_CONS FOREIGN KEY(COD_CONSULENZA) REFERENCES CONSULENZA(COD_CONSULENZA) ON DELETE CASCADE);

CREATE TABLE CATEGORIA(
NOME VARCHAR(15),
IVA NUMBER NOT NULL,
CONSTRAINT PK_CATEGORIA PRIMARY KEY (NOME));

CREATE TABLE VALUTA(
CF_ESPERTO CHAR(16),
TARIFFA NUMBER NOT NULL,
NOME_CAT VARCHAR2(15),
CONSTRAINT PK_VALUTA PRIMARY KEY (CF_ESPERTO,NOME_CAT),
CONSTRAINT FK_CFESP2 FOREIGN KEY(CF_ESPERTO) REFERENCES ESPERTO(CF) ON DELETE CASCADE,
CONSTRAINT FK_NOMECAT FOREIGN KEY(NOME_CAT) REFERENCES CATEGORIA(NOME) ON DELETE CASCADE);
---------------------------------------------------------------------------------------------
CREATE TABLE TELEFONOFORNITORI(
PIVA CHAR(11) NOT NULL,
TELEFONO CHAR(10),
CONSTRAINT CHK_TELEFONO1 CHECK(REGEXP_LIKE(TELEFONO,'^[0-9]')),
CONSTRAINT PK_TELEFONOF PRIMARY KEY(PIVA,TELEFONO),
CONSTRAINT FK_FORNITORE2 FOREIGN KEY (PIVA) REFERENCES FORNITORE(PIVA) ON DELETE CASCADE);

CREATE TABLE TELEFONOPERSONA(
CF CHAR(16) NOT NULL,
TELEFONO CHAR(10),
CONSTRAINT CHK_TELEFONO2 CHECK(REGEXP_LIKE(TELEFONO,'^[0-9]')),
CONSTRAINT PK_TELEFONOP PRIMARY KEY(CF,TELEFONO),
CONSTRAINT FK_PERSONA FOREIGN KEY (CF) REFERENCES PERSONA(CODICE_FISCALE) ON DELETE CASCADE);

CREATE TABLE TELEFONOESPERTO(
CF_ESP CHAR(16) NOT NULL,
TELEFONO CHAR(10) NOT NULL,
CONSTRAINT CHK_TELEFONO3 CHECK(REGEXP_LIKE(TELEFONO,'^[0-9]')),
CONSTRAINT PK_TELEFONOE PRIMARY KEY(CF_ESP,TELEFONO),
CONSTRAINT FK_ESPERTO FOREIGN KEY (CF_ESP) REFERENCES ESPERTO(CF) ON DELETE CASCADE);

-- LE SEQUENZE CONSENTE DI DEFINIRE UN GENERATORE DI SEQUENZE NUMERICHE.
-- QUESTE SONO UTILI PER GENERARE CHIAVI ARTIFICIALE PER IDENTIFICARE LE
-- LE TUPLE DI UNA TABELLA. AD OGNI INSERIMENTO VIENE GENERATO IL NUMERO
-- SUCCESSIVO ASSEGNATO ALLA TUPLA PRECEDENTE

DROP SEQUENCE SEQ_CODART;
DROP SEQUENCE SEQ_IDFAMASS;
DROP SEQUENCE SEQ_CODPEGNO;
DROP SEQUENCE SEQ_CODMOVIMENTO;
DROP SEQUENCE SEQ_CODRISCATTO;
DROP SEQUENCE SEQ_CODOGG;
DROP SEQUENCE SEQ_CODCONS;

CREATE SEQUENCE SEQ_CODART
START WITH 31 INCREMENT BY 1
MINVALUE 31 MAXVALUE 1000000
CYCLE CACHE 10 ORDER;

CREATE SEQUENCE SEQ_IDFAMASS
START WITH 7 INCREMENT BY 1
MINVALUE 7 MAXVALUE 1000000
CYCLE CACHE 10 ORDER;

CREATE SEQUENCE SEQ_CODPEGNO
START WITH 13 INCREMENT BY 1
MINVALUE 13 MAXVALUE 1000000
CYCLE CACHE 10 ORDER;

CREATE SEQUENCE SEQ_CODMOVIMENTO
START WITH 3 INCREMENT BY 1
MINVALUE 3 MAXVALUE 1000000
CYCLE CACHE 10 ORDER;

CREATE SEQUENCE SEQ_CODRISCATTO
START WITH 5 INCREMENT BY 1
MINVALUE 5 MAXVALUE 1000000
CYCLE CACHE 10 ORDER;

CREATE SEQUENCE SEQ_CODOGG
START WITH 44 INCREMENT BY 1
MINVALUE 44 MAXVALUE 1000000
CYCLE CACHE 10 ORDER;

CREATE SEQUENCE SEQ_CODCONS
START WITH 101 INCREMENT BY 1
MINVALUE 101 MAXVALUE 1000000
CYCLE CACHE 10 ORDER;