CREATE OR REPLACE TRIGGER PROROGA_PEGNO
BEFORE UPDATE OF PROROGA ON PEGNO
FOR EACH ROW
DECLARE
EX1 EXCEPTION;
EX2 EXCEPTION;
EX3 EXCEPTION;
EX4 EXCEPTION;
BEGIN
IF ROUND(MONTHS_BETWEEN(SYSDATE,:OLD.DATA_PEGNO),0)>12 THEN RAISE EX1;
ELSE IF :OLD.PROROGA=1 AND ROUND(MONTHS_BETWEEN(SYSDATE,:OLD.DATA_PEGNO),0)>12 THEN RAISE EX2;
ELSE IF :OLD.PROROGA=2 AND ROUND(MONTHS_BETWEEN(SYSDATE,:OLD.DATA_PEGNO),0)>12 THEN RAISE EX3;
ELSE IF :OLD.PROROGA=3 THEN RAISE EX4;
END IF;
END IF;
END IF;
END IF;
EXCEPTION
WHEN EX1 THEN
RAISE_APPLICATION_ERROR(-20016,'ATTENZIONE: IMPOSSIBILE PROROGARE IL PEGNO, OGGETTO NON PIU RISCATTABILE');
WHEN EX2 THEN
RAISE_APPLICATION_ERROR(-20017,'ATTENZIONE: IMPOSSIBILE PROROGARE IL PEGNO, OGGETTO NON PIU RISCATTABILE');
WHEN EX3 THEN
RAISE_APPLICATION_ERROR(-20018,'ATTENZIONE: IMPOSSIBILE PROROGARE IL PEGNO, PEGNO NON PIU PROROGABILE');
WHEN EX4 THEN
RAISE_APPLICATION_ERROR(-20019,'ATTENZIONE: IMPOSSIBILE PROROGARE IL PEGNO');
END;
/
