CREATE OR REPLACE TRIGGER NUM_PEGNI_GIORNALIERI
BEFORE INSERT ON PEGNO
FOR EACH ROW
DECLARE
EX1 EXCEPTION;
CONTP NUMBER;
BEGIN
SELECT COUNT(COD_PEGNO) INTO CONTP
FROM PEGNO
WHERE TO_CHAR(DATA_PEGNO,'DD-MM-YYYY')=TO_CHAR(SYSDATE,'DD-MM-YYYY');
IF CONTP>=10 THEN
RAISE EX1;
END IF;
EXCEPTION
WHEN EX1 THEN
RAISE_APPLICATION_ERROR(-20200,'ATTENZIONE: IMPOSSIBILE REGISTRATE ALTRI PEGNI PER OGGI');
END;
/