CREATE OR REPLACE VIEW QTDISP_ARTICOLI AS SELECT A.CODART,NVL(
((SELECT SUM(QTACQUISTATA) FROM CONTIENE
WHERE CODART=A.CODART)-(SELECT SUM(QTVENDUTA)
FROM RIGUARDA
WHERE CODART=A.CODART)),0) AS DISP
FROM ARTICOLO A GROUP BY A.CODART ORDER BY A.CODART
/